export type TokenMode = 'light' | 'dark';

export const designTokens = {
  typography: {
    fontFamily:
      "Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    size: {
      xs: '12px',
      sm: '14px',
      md: '16px',
      lg: '18px',
      xl: '24px',
      '2xl': '34px',
      '3xl': '40px',
    },
    weight: {
      regular: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
      black: 800,
    },
  },
  spacing: {
    1: '4px',
    2: '8px',
    3: '12px',
    4: '16px',
    5: '20px',
    6: '24px',
    8: '32px',
    10: '40px',
    12: '48px',
  },
  radius: {
    none: '0px',
    sm: '8px',
    md: '12px',
    lg: '16px',
    xl: '20px',
    '2xl': '28px',
    '3xl': '34px',
    full: '9999px',
  },
  shadow: {
    sm: '0 8px 20px rgba(2, 15, 23, 0.06)',
    md: '0 14px 28px rgba(2, 15, 23, 0.08)',
    lg: '0 20px 45px rgba(2, 15, 23, 0.10)',
    glow: '0 18px 40px rgba(3, 205, 140, 0.14)',
  },
  color: {
    brand: {
      primary: '#03cd8c',
      primaryStrong: '#00b57a',
      primarySoft: '#d7f5e8',
    },
    accent: {
      primary: '#f77f00',
      soft: '#fff1df',
    },
    neutral: {
      ink: '#0f172a',
      slate: '#64748b',
      line: '#e2e8f0',
      paper: '#ffffff',
      pageBg: '#f4f8f6',
      surface: '#f8fafc',
      mediumGrey: '#a6a6a6',
      lightGrey: '#f2f2f2',
    },
    dark: {
      ink: '#e2e8f0',
      slate: '#94a3b8',
      line: '#334155',
      paper: '#0f172a',
      pageBg: '#0b1220',
      surface: '#111b2f',
    },
  },
} as const;

export const brandTokens = {
  green: designTokens.color.brand.primary,
  greenDark: designTokens.color.brand.primaryStrong,
  greenSoft: designTokens.color.brand.primarySoft,
  orange: designTokens.color.accent.primary,
  orangeSoft: designTokens.color.accent.soft,
  mediumGrey: designTokens.color.neutral.mediumGrey,
  lightGrey: designTokens.color.neutral.lightGrey,
  ink: designTokens.color.neutral.ink,
  slate: designTokens.color.neutral.slate,
  paper: designTokens.color.neutral.paper,
  surface: designTokens.color.neutral.surface,
  line: designTokens.color.neutral.line,
} as const;

export function getCssThemeVariables(mode: TokenMode): Record<string, string> {
  const isDark = mode === 'dark';
  return {
    '--fh-font-family': designTokens.typography.fontFamily,
    '--fh-font-size-xs': designTokens.typography.size.xs,
    '--fh-font-size-sm': designTokens.typography.size.sm,
    '--fh-font-size-md': designTokens.typography.size.md,
    '--fh-font-size-lg': designTokens.typography.size.lg,
    '--fh-font-size-xl': designTokens.typography.size.xl,
    '--fh-font-size-2xl': designTokens.typography.size['2xl'],
    '--fh-font-size-3xl': designTokens.typography.size['3xl'],
    '--fh-radius-sm': designTokens.radius.sm,
    '--fh-radius-md': designTokens.radius.md,
    '--fh-radius-lg': designTokens.radius.lg,
    '--fh-radius-xl': designTokens.radius.xl,
    '--fh-radius-2xl': designTokens.radius['2xl'],
    '--fh-radius-3xl': designTokens.radius['3xl'],
    '--fh-shadow-sm': designTokens.shadow.sm,
    '--fh-shadow-md': designTokens.shadow.md,
    '--fh-shadow-lg': designTokens.shadow.lg,
    '--fh-shadow-glow': designTokens.shadow.glow,
    '--fh-brand': designTokens.color.brand.primary,
    '--fh-brand-dark': designTokens.color.brand.primaryStrong,
    '--fh-brand-soft': designTokens.color.brand.primarySoft,
    '--fh-accent': designTokens.color.accent.primary,
    '--fh-accent-soft': designTokens.color.accent.soft,
    '--fh-ink': isDark ? designTokens.color.dark.ink : designTokens.color.neutral.ink,
    '--fh-slate': isDark ? designTokens.color.dark.slate : designTokens.color.neutral.slate,
    '--fh-line': isDark ? designTokens.color.dark.line : designTokens.color.neutral.line,
    '--fh-surface': isDark ? designTokens.color.dark.surface : designTokens.color.neutral.surface,
    '--fh-page-bg': isDark ? designTokens.color.dark.pageBg : designTokens.color.neutral.pageBg,
    '--fh-surface-bg': isDark ? designTokens.color.dark.paper : designTokens.color.neutral.paper,
  };
}
