export const providerRoutes = {
  root: '/faithhub/provider',
  dashboardUi: '/dashboard-ui',
  dashboard: '/faithhub/provider/dashboard',
  services: '/faithhub/provider/services',
  liveDashboard: '/faithhub/provider/live-dashboard',
  liveBuilder: '/faithhub/provider/live-builder',
  liveSchedule: '/faithhub/provider/live-schedule',
  liveStudio: '/faithhub/provider/live-studio',
  liveSessionDetails: '/faithhub/provider/live-session-details',
  waitingRoom: '/faithhub/provider/waiting-room',
  teachingsDashboard: '/faithhub/provider/teachings-dashboard',
  seriesDashboard: '/faithhub/provider/series-dashboard',
  resourcesManager: '/faithhub/provider/resources-manager',
  workspaceSettings: '/faithhub/provider/workspace-settings',
  profileSettings: '/faithhub/provider/profile-settings',
  onboarding: '/faithhub/provider/onboarding',
  reviewsAndModeration: '/faithhub/provider/reviews-and-moderation',
  communityGroups: '/faithhub/provider/community-groups',
  campaigns: '/faithhub/provider/campaigns',
  campaignBuilder: '/faithhub/provider/campaign-builder',
  serviceBuilder: '/faithhub/provider/service-builder',
  contentUpload: '/faithhub/provider/content-upload',
  audienceNotifications: '/faithhub/provider/audience-notifications',
  noticeboard: '/faithhub/provider/noticeboard',
  postLivePublishing: '/faithhub/provider/post-live-publishing',
  replaysAndClips: '/faithhub/provider/replays-and-clips',
  donationsAndFunds: '/faithhub/provider/donations-and-funds',
  charityCrowdfundingWorkbench: '/faithhub/provider/charity-crowdfunding-workbench',
  walletPayouts: '/faithhub/provider/wallet-payouts',
  revelightDashboard: '/faithhub/provider/revelight-dashboard',
  revelightMarketplace: '/faithhub/provider/revelight-marketplace',
  standaloneTeachingBuilder: '/faithhub/provider/standalone-teaching-builder',
  merchandiseBuilder: '/faithhub/provider/merchandise-builder',
  eventsManager: '/faithhub/provider/events-manager',
  projects: '/faithhub/provider/projects',
  prayerRequests: '/faithhub/provider/prayer-requests',
  testimonies: '/faithhub/provider/testimonies',
  counseling: '/faithhub/provider/counseling',
  devotionals: '/faithhub/provider/devotionals',
  rolesPermissions: '/faithhub/provider/roles-permissions',
  servingTeams: '/faithhub/provider/serving-teams',
  moderationSettings: '/faithhub/provider/moderation-settings',
} as const;

export type ProviderRouteKey = keyof typeof providerRoutes;
